import fs from "node:fs/promises";
import path from "node:path";
import { getRunDir, readEvents, readMeta } from "./store.js";

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatMs(ms) {
  if (ms === undefined) return "—";
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function statusClass(status) {
  if (status === "passed") return "ok";
  if (status === "running") return "run";
  return "fail";
}

function renderEvents(events) {
  return events
    .map((e) => {
      const sec = (e.t / 1000).toFixed(3);
      return `<div class="line ${e.kind}"><span class="t">+${sec}s</span><span class="k">${e.kind}</span><pre>${escapeHtml(e.text)}</pre></div>`;
    })
    .join("\n");
}

export async function writeReport(id, outPath) {
  const meta = await readMeta(id);
  const events = await readEvents(id);
  const html = buildHtml(meta, events);
  const target = outPath || path.join(getRunDir(id), "report.html");
  await fs.writeFile(target, html, "utf8");
  return target;
}

export function buildHtml(meta, events) {
  const cmd = meta.command.join(" ");
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Runshot — ${escapeHtml(cmd)}</title>
  <style>
    :root {
      --bg: #0f1419;
      --panel: #171d25;
      --text: #e7ecf3;
      --muted: #8b98a8;
      --ok: #3dd68c;
      --fail: #ff6b6b;
      --run: #5bb8ff;
      --line: #243041;
      --stdout: #cfe3ff;
      --stderr: #ffc9c2;
      --system: #9aa8b8;
      --accent: #e8a54b;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
      background:
        radial-gradient(1200px 600px at 10% -10%, #243247 0%, transparent 55%),
        radial-gradient(900px 500px at 100% 0%, #2a2118 0%, transparent 50%),
        var(--bg);
      color: var(--text);
      min-height: 100vh;
    }
    header {
      padding: 2.5rem 2rem 1.25rem;
      border-bottom: 1px solid var(--line);
    }
    .brand {
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      font-size: 0.75rem;
      color: var(--accent);
      margin-bottom: 0.75rem;
    }
    h1 {
      font-size: 1.35rem;
      font-weight: 600;
      margin: 0 0 1rem;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      word-break: break-word;
    }
    .meta {
      display: flex;
      flex-wrap: wrap;
      gap: 0.75rem 1.25rem;
      color: var(--muted);
      font-size: 0.9rem;
    }
    .pill {
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
      padding: 0.2rem 0.55rem;
      border-radius: 4px;
      border: 1px solid var(--line);
      background: var(--panel);
    }
    .pill.ok { color: var(--ok); border-color: #255a42; }
    .pill.fail { color: var(--fail); border-color: #6a3030; }
    .pill.run { color: var(--run); border-color: #2a4d6a; }
    main { padding: 1.25rem 2rem 3rem; max-width: 1100px; }
    .line {
      display: grid;
      grid-template-columns: 5.5rem 4.5rem 1fr;
      gap: 0.75rem;
      padding: 0.45rem 0;
      border-bottom: 1px solid #1c2430;
      align-items: start;
    }
    .t, .k {
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.75rem;
      color: var(--muted);
      padding-top: 0.2rem;
    }
    pre {
      margin: 0;
      white-space: pre-wrap;
      word-break: break-word;
      font-family: "IBM Plex Mono", ui-monospace, monospace;
      font-size: 0.82rem;
      line-height: 1.45;
    }
    .stdout pre { color: var(--stdout); }
    .stderr pre { color: var(--stderr); }
    .system pre { color: var(--system); font-style: italic; }
    footer {
      padding: 1rem 2rem 2rem;
      color: var(--muted);
      font-size: 0.8rem;
    }
    a { color: var(--accent); }
  </style>
</head>
<body>
  <header>
    <div class="brand">Runshot report</div>
    <h1>${escapeHtml(cmd)}</h1>
    <div class="meta">
      <span class="pill ${statusClass(meta.status)}">${escapeHtml(meta.status)}</span>
      <span class="pill">exit ${meta.exitCode ?? "—"}</span>
      <span class="pill">${formatMs(meta.durationMs)}</span>
      <span class="pill">${escapeHtml(meta.startedAt)}</span>
      <span class="pill">${events.length} events</span>
    </div>
  </header>
  <main>
    ${renderEvents(events) || '<p class="meta">No events captured.</p>'}
  </main>
  <footer>
    Generated by <a href="https://github.com/runshot/runshot">Runshot</a> — local run capture for developers.
  </footer>
</body>
</html>`;
}
